# Deep Understanding of Deep Learning Practice
## Topic: Math,Numpy,Pytorch
#### Topic: Vector and Matrix Transpose

### Shahjalal Shanto
##### Department of Chemistry, University of Chittagong
**February 02,2024**

In [2]:
#Import Librarries
import numpy as np
import torch 

## Using Numpy

### Vector
*vector is simply a one-dimensional array.*

In [28]:
#Creating a Vector Using Numpy
a = np.array([2,4,-10,20])
print(a)

[  2   4 -10  20]


In [29]:
#Transposing a Vector
a.T
#nothing has changed

array([  2,   4, -10,  20])

In [9]:
#Shape of a 
a.shape

(4,)

In [10]:
#Size of a 
a.size

4

In [12]:
# creating a Vector for tranposing
aV = np.array([[2,   4, -10,  20]])
print(aV)

[[  2   4 -10  20]]


In [13]:
# Transposing aV
aV.T

array([[  2],
       [  4],
       [-10],
       [ 20]])

In [42]:
#Shape of aV
print(f" Shape of aV Vector: {aV.shape}")
#Size of aV
print(f" Size of aV Vector: {aV.size}")
#type of aV
print(f" Type of aV Vector: {type(aV)}")

 Shape of aV Vector: (1, 4)
 Size of aV Vector: 4
 Type of aV Vector: <class 'numpy.ndarray'>


*Transposing the Transpose will back to its Original*

In [31]:
print(f"This is a Original aV vector: {aV}")
print(" ")
print(f"This is aV vector after Transposing: \n {aV.T}")
print(" ")
print(f"This is Original Vector after transposing the Transpose Vector: {(aV.T).T}")

This is a Original aV vector: [[  2   4 -10  20]]
 
This is aV vector after Transposing: 
 [[  2]
 [  4]
 [-10]
 [ 20]]
 
This is Original Vector after transposing the Transpose Vector: [[  2   4 -10  20]]


### Matrix
*matrix is a 2 dimensional array of numbers*

In [32]:
nM = np.array([[1,2,3,4],
               [5,6,7,8]
              ])
print(nM)

[[1 2 3 4]
 [5 6 7 8]]


In [41]:
#Shape
print(f"Shape of nM: {nM.shape}")
print(" ")
#size
print(f"Size of nM: {nM.size}"), print(" ")
#Type
print(f"The type of nM Matrix: {type(nM)}")

Shape of nM: (2, 4)
 
Size of nM: 8
 
The type of nM Matrix: <class 'numpy.ndarray'>


In [38]:
#Transposing the Matrix
print(nM.T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [39]:
##Transposing the Transpose Matrix
print((nM.T).T)

[[1 2 3 4]
 [5 6 7 8]]


## Using Pytorch

In [47]:
#Creating Vector
tV= torch.tensor([[1,2,3,4]])
print(tV)

tensor([[1, 2, 3, 4]])


In [57]:
#Shape
print(f"Shape of tV: {tV.shape}"), print(" ")
#Size
print(f"Size of tV: {tV.size()}"), print(" ")
#Type
print(f"type of tV: {type(tV)}")

Shape of tV: torch.Size([1, 4])
 
Size of tV: torch.Size([1, 4])
 
type of tV: <class 'torch.Tensor'>


**A tensor is a generic structure that can be used for storing, repmresenting, and changing data.**

In [51]:
#Transposing a Vector in pytorch
print(f"Original Vector: {tV}"), print(" ")
print(f'After Transposing: \n {tV.T}'), print(" ")
print(f"After tranposing the transpose Vector: {(tV.T).T}")

Original Vector: tensor([[1, 2, 3, 4]])
 
After Transposing: 
 tensor([[1],
        [2],
        [3],
        [4]])
 
After tranposing the transpose Vector: tensor([[1, 2, 3, 4]])


In [60]:
### Matrix Using Pytorchx
tm = torch.tensor(
    [
    [1,2,3,4],
    [5,6,7,8]
    ])
print(tm)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])


In [62]:
#Shape
print(f"Shape of tm Matrix: {tm.shape}"), print(" ")
#Size
print(f"Size of tm Matrix: {tm.size()}"), print(" ")
#Type
print(f"type of tm Matrix: {type(tm)}")

Shape of tm Matrix: torch.Size([2, 4])
 
Size of tm Matrix: torch.Size([2, 4])
 
type of tm Matrix: <class 'torch.Tensor'>


In [64]:
#Transposing a Matrix in pytorch
print(f"Original Matrix: {tm}"), print(" ")
print(f'After Transposing: \n {tm.T}'), print(" ")
print(f"After tranposing the transpose Matrix: {(tm.T).T}")

Original Matrix: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
 
After Transposing: 
 tensor([[1, 5],
        [2, 6],
        [3, 7],
        [4, 8]])
 
After tranposing the transpose Matrix: tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])
