# Deep Understanding of Deep Learning Practice
## Chapter: Statistics,Numpy,Pytorch
### Topic: Minimum(argmin), Maximum(argmax)
#### Shahjalal Shanto
##### Department of Chemistry, University of Chittagong
**25 February 2024**

In [3]:
#importing Libraries
import numpy as np
import matplotlib.pyplot as plt
import torch
import torch.nn as nn

**Note:**
* In DL(for example in CNN), in a list of Model Output the argmax function help us to determine which has the highest softmax value that was given by a softmax function

## Using numpy

In [5]:
#Creating a random vector
vec = np.random.randint(-5,5,20)
print(vec)

[-3 -5  4 -1  1 -4  3  3 -3 -4  0  2  3  4 -4  1  3  0  0 -1]


In [6]:
#minimum value
minval = np.min(vec)
#maximum value
maxval = np.max(vec)

print("Min,Max: %g,%g" %(minval,maxval))

Min,Max: -5,4


In [7]:
#now for the argmin and aargmax
minidx = np.argmin(vec)
maxidx = np.argmax(vec)
print("minimum,maximum indices: %g,%g"%(minidx,maxidx))

minimum,maximum indices: 1,2


In [9]:
#Confirm
print(f"Minimum value is {vec[minidx]} and Maximum Value is {vec[maxidx]}")

Minimum value is -5 and Maximum Value is 4


**Repeating With Matrix**

In [11]:
#creating a random matrix
rmat = np.random.rand(3,2)
rmat

array([[0.55127617, 0.64295418],
       [0.80987604, 0.69215204],
       [0.6754636 , 0.23488575]])

In [14]:
minvals1 = np.min(rmat) #minimum value from the entire matrix
minval_in_column = np.min(rmat,axis=0) #minimum value across column
minval_in_row = np.min(rmat,axis=1) #minimum value across row
print(f"minimum value of the entire matrix: {minvals1}"), print(" ")
print(f"minimum value in each column: {minval_in_column}"), print(" ")
print(f"minimum value in each row: {minval_in_row}"), print(" ")

minimum value of the entire matrix: 0.23488574633329218
 
minimum value in each column: [0.55127617 0.23488575]
 
minimum value in each row: [0.55127617 0.69215204 0.23488575]
 


(None, None)

In [15]:
#repeating for argmin
minvalidx = np.argmin(rmat) #in the entire matrix
minvalidx_in_col = np.argmin(rmat,axis=0) #index of minimum value across column
minvalidx_in_row = np.argmin(rmat,axis=1) #index of minimum value across row
print(f"Index of minimum value of the entire matrix: {minvalidx}"), print(" ")
print(f"Index of minimum value in each column: {minvalidx_in_col}"), print(" ")
print(f"Index of minimum value in each row: {minvalidx_in_row}"), print(" ")

Index of minimum value of the entire matrix: 5
 
Index of minimum value in each column: [0 2]
 
Index of minimum value in each row: [0 1 1]
 


(None, None)

## Using pytorch

In [17]:
#Converting the vector to tensor
vt = torch.Tensor(vec)
vt

tensor([-3., -5.,  4., -1.,  1., -4.,  3.,  3., -3., -4.,  0.,  2.,  3.,  4.,
        -4.,  1.,  3.,  0.,  0., -1.])

In [19]:
#minimum and maximum
tmin = torch.min(vt)
tmax = torch.max(vt)
print("Minimum,Maximum: %g,%g"%(tmin,tmax))

Minimum,Maximum: -5,4


In [21]:
#index of minimum and maximum
tminidx = torch.argmin(vt)
tmaxidx = torch.argmax(vt)
print("Index of Minimum and Maximum: %g,%g" %(tminidx,tmaxidx))

Index of Minimum and Maximum: 1,2


**Repeating the process for Matrix**

In [23]:
tmat = torch.Tensor(rmat)
tmat

tensor([[0.5513, 0.6430],
        [0.8099, 0.6922],
        [0.6755, 0.2349]])

In [25]:
#finding minimam in a matrix using pytorch
mint = torch.min(tmat) #in the entire matrix
minInCol = torch.min(tmat,axis=0) #minimum across column
minInRow = torch.max(tmat,axis=1)  #minimum across row
print(f"minimum value of the entire matrix: {mint}"), print(" ")
print(f"minimum value in each column: {minInCol}"), print(" ")
print(f"minimum value in each row: {minInRow}"), print(" ")

minimum value of the entire matrix: 0.23488575220108032
 
minimum value in each column: torch.return_types.min(
values=tensor([0.5513, 0.2349]),
indices=tensor([0, 2]))
 
minimum value in each row: torch.return_types.max(
values=tensor([0.6430, 0.8099, 0.6755]),
indices=tensor([1, 0, 0]))
 


(None, None)

**Its a different data types, not a tensor. we dont have to find the indices separately the values and the indices are given in a tuple**

In [26]:
type(minInCol)

torch.return_types.min

In [28]:
#we can extract values and indices separately
minInCol.values

tensor([0.5513, 0.2349])

In [31]:
#indices
minInCol.indices

tensor([0, 2])